### ISSUE TITLE
RuntimeWarning: divide by zero encountered in true_divide

### ISSUE THREAD

**Issue by tsiakmaki** [sorend/fylearn#13]
I am getting the: 
```
/home/user/.virtualenvs/fuzzylearning/lib/python3.5/site-packages/fylearn/frr.py:150: 
RuntimeWarning: divide by zero encountered in true_divide
  return 2 ** -((np.abs(m - S) / C) ** self.D)
```
warning when testing the `ModifiedFuzzyPatternClassifier` for my dataset. 
As such the result accuracy is small, e.g. 0.1955
Any suggestions why? 

ps. Thank you for your code distribution and for your time.

**Comment by sorend** [comment]
Hi @tsiakmaki :

Could it be that you have a feature with only a single value in your dataset?  If you are able to share the dataset please link it.

(the code should naturally work also in this case, just trying to determine the cause)

Best regards,
Soren

**Comment by tsiakmaki** [comment]
I am sorry, but I could not share our datasets. 
The ones with the warning are imbalanced. 
E.g. one has 40 features and 130 instances: 105 for classA and 25 for classB.
and i am using 10 folds. 
Just tried using a sampler before fitting the model, and I am not getting the warning any more.
