### ISSUE TITLE
Get number of rules

### ISSUE THREAD

**Issue by jorjasso** [sorend/fylearn#16]
It is possible to implement a method to get the number of rules of the final estimator?

**Comment by sorend** [comment]
Hi @jorjasso -- any specific estimator from the library you're thinking of?

**Comment by jorjasso** [comment]
BTW, nice work you did, thanks for that :). I dont know the details of every implemented classifier on this library but it will be nice to estimate the number of rules of rule-based classifiers, (In the future the rules could also be retrieved).  Another nice thing to have is  a set of examples for model selection of those classifiers, i.e. what are the set of hyper-parameters to be optimized in model selection procedures by random/grid search?
