### ISSUE TITLE
How to add multiple variables(subjects) by using lower bound and upper bound?

### ISSUE THREAD

**Issue by alanthomass** [sorend/fylearn#17]
Hey, Thanks for this work in python. My query is the follwoing:
How can we implement this code to minimise my objective function, if i have multiple variables in the function that i wish to create? I am unable to define multiple variables at the moment inside the function.

say,  i wish to minimise the function 2*x+ 10*x**2 +32* z+35*z**2 +  x*z ,  with x [-5,5] and z [-5,5], How can we do that, since the TLBO generates variables based on bounds, how to use that variables in my function. Hope you can help me?

Regards,
Alan

**Comment by alanthomass** [comment]
2x + 10x^2 +32z + 35z^2 +xz

**Comment by sorend** [comment]
Do you have code to share?

Have you seen the example in the tests?
https://github.com/sorend/fylearn/blob/master/tests/test_tlbo.py#L32

You need to decide on upper and lower bounds for your variables, but you can set them as you like. In the current implementation you cannot set them as inf and -inf as the bounds are used to determine initial solutions. You can however work around this if you desire.

**Comment by alanthomass** [comment]
![image](https://user-images.githubusercontent.com/65440327/82114672-d6477400-977b-11ea-8354-124a4382a603.png)

![image](https://user-images.githubusercontent.com/65440327/82114691-f5460600-977b-11ea-9f4c-833b22442149.png)

**Comment by alanthomass** [comment]
i cant fit values for other variables:(

**Comment by alanthomass** [comment]
why cant i load multiple variables?How to do that?Can you help me?

**Comment by sorend** [comment]
```
def fitness(X):
  x1, x2, x3, x4 = X
  # rest of your code here
```
Closing this issue.

**Comment by alanthomass** [comment]
Thank you for the prompt response. It is still showing an error, even though i added 4 values to unpack. 
![image](https://user-images.githubusercontent.com/65440327/82118837-5929f800-9797-11ea-9628-c71b26d798a5.png)
![image](https://user-images.githubusercontent.com/65440327/82118859-76f75d00-9797-11ea-9784-ef2b4b504fbf.png)
