### ISSUE TITLE
Follow up on the previous query

### ISSUE THREAD

**Issue by alanthomass** [sorend/fylearn#18]
Hey, Thanks for the response. Am still facing an issue with unpacking.
![image](https://user-images.githubusercontent.com/65440327/82120985-68b13d00-97a7-11ea-9d0b-b41c19dff1f4.png)

![image](https://user-images.githubusercontent.com/65440327/82120960-37387180-97a7-11ea-9837-7da43f56b2ec.png)

**Comment by sorend** [comment]
I see a problem with later numpy. I have fixed it in 0.1.9, try to upgrade, and report back here if it does not solve your problem (you can see something like your problem covered the automated test: https://github.com/sorend/fylearn/blob/master/tests/test_tlbo.py#L66 )

Thanks for reporting.

BR,
Soren

**Comment by alanthomass** [comment]
![image](https://user-images.githubusercontent.com/65440327/82152300-d0d25280-987d-11ea-9808-f18055f9ecb8.png)
![image](https://user-images.githubusercontent.com/65440327/82152316-e2b3f580-987d-11ea-9aef-0f1fa3d977ea.png)
![image](https://user-images.githubusercontent.com/65440327/82152323-f3646b80-987d-11ea-83db-ba49c3575f6f.png)
![image](https://user-images.githubusercontent.com/65440327/82152332-02e3b480-987e-11ea-97f3-08d143e01bdc.png)

**Comment by alanthomass** [comment]
I tried the above automated test link code you shared. Still found the same error. You can see in a line that the length turns out to be 1.

**Comment by sorend** [comment]
@alanthomass Can you share full code (not screenshots) of your example that fails?

Also please share the output from "pip freeze" so I can see which versions you're running on.

Thanks.

**Comment by alanthomass** [comment]
```
import pandas as pd
import numpy as np
from fylearn.ga import UnitIntervalGeneticAlgorithm, helper_fitness, helper_n_generations
from fylearn.local_search import LocalUnimodalSamplingOptimizer, helper_num_runs
from fylearn.tlbo import TeachingLearningBasedOptimizer
def fitness(X):
        print("X", X, "len", len(X))
        x1, x2, x3, x4 = X.tolist()
        return 0.0358 +(0.7349*x1) + (.0578*x2)-(0.3151*x3) + (0.6888*x4) + (0.1803*(x1**2)) -(0.0481* 
       (x2**2)) + (0.1699*(x3**2)) - (0.0494*(x4**2))- (0.3555*(x1*x2)) - (0.6316*(x1*x3)) + (0.5973* 
       (x1*x4)) + (0.0826*(x2*x3)) - (0.4736*(x2*x4)) -  (0.6547*(x3*x4))

lower_bounds = np.array([-10,-10,-10,-10])
upper_bounds = np.array([10,10,10,10])
    

tlbo = TeachingLearningBasedOptimizer(fitness, lower_bounds, upper_bounds)
tlbo = helper_n_generations(tlbo, 100)
best_solution, best_fitness = tlbo.best()
print("TLBO solution", best_solution, "fitness", best_fitness)
```

**Comment by alanthomass** [comment]
return 0.0358 +(0.7349x1) + (.0578x2)-(0.3151x3) + (0.6888x4) + (0.1803*(x12)) -(0.0481*
(x2**2)) + (0.1699*(x3**2)) - (0.0494*(x4**2))- (0.3555*(x1x2)) - (0.6316(x1x3)) + (0.5973
(x1x4)) + (0.0826(x2x3)) - (0.4736(x2x4)) - (0.6547(x3*x4))

this was the return code :)

**Comment by alanthomass** [comment]
(base) C:\Users\Hp>pip freeze
absl-py==0.9.0
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
appdirs==1.4.3
argh==0.26.2
asn1crypto==1.3.0
astor==0.8.1
astroid==2.3.3
astropy==4.0
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.4.4
Babel==2.8.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.1.7
beautifulsoup4==4.8.2
bitarray==1.2.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.4.0
boto==2.49.0
Bottleneck==1.3.2
cachetools==4.1.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
Click==7.0
cloudpickle==1.3.0
clyent==1.2.2
colorama==0.4.3
comtypes==1.1.7
conda==4.8.3
conda-build==3.18.11
conda-package-handling==1.6.0
conda-verify==3.4.2
contextlib2==0.6.0.post1
cryptography==2.8
cycler==0.10.0
Cython==0.29.15
cytoolz==0.10.1
dask==2.11.0
decorator==4.4.1
defusedxml==0.6.0
diff-match-patch==20181111
distlib==0.3.0
distributed==2.11.0
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
flake8==3.7.9
Flask==1.1.1
fsspec==0.6.2
future==0.18.2
fylearn==0.1.8
gast==0.2.2
gevent==1.4.0
glob2==0.7
google-auth==1.14.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
greenlet==0.4.15
grpcio==1.28.1
h5py==2.10.0
HeapDict==1.0.1
html5lib==1.0.1
hypothesis==5.5.4
idna==2.8
imageio==2.6.1
imagesize==1.2.0
importlib-metadata==1.5.0
intervaltree==3.0.2
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.14.1
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
jupyterlab==1.2.6
jupyterlab-server==1.0.6
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==21.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
libarchive-c==2.8
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==4.0.1
more-itertools==8.2.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
nltk==3.4.5
nose==1.3.7
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.18.1
numpydoc==0.9.2
oauthlib==3.1.0
olefile==0.46
openpyxl==3.0.3
opt-einsum==3.2.1
packaging==20.1
pandas==1.0.1
pandocfilters==1.4.2
paramiko==2.7.1
parso==0.5.2
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pkginfo==1.5.0.1
pluggy==0.13.1
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.3
protobuf==3.11.3
psutil==5.6.7
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.5
pydocstyle==4.0.1
pyflakes==2.1.1
Pygments==2.5.2
pylint==2.4.4
PyNaCl==1.3.0
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyreadline==2.1
pyrsistent==0.15.7
PySocks==1.7.1
pyswarm==0.6
pyswarms==1.1.0
pytest==5.3.5
pytest-arraydiff==0.3
pytest-astropy==0.8.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.5.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.7
pytz==2019.3
PyWavelets==1.1.1
pywin32==227
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.3
pyzmq==18.1.1
QDarkStyle==2.8
QtAwesome==0.6.1
qtconsole==4.6.0
QtPy==1.9.0
requests==2.22.0
requests-oauthlib==1.3.0
rope==0.16.0
rsa==4.0
Rtree==0.9.3
ruamel-yaml==0.15.87
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.14.0
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.5
Sphinx==2.4.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.2.0
spyder==4.0.1
spyder-kernels==1.8.1
SQLAlchemy==1.3.13
statsmodels==0.11.0
sympy==1.5.1
tables==3.6.1
tblib==1.6.0
tensorboard==2.1.1
tensorflow==2.1.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.3
tqdm==4.42.1
traitlets==4.3.3
ujson==1.35
unicodecsv==0.14.1
urllib3==1.25.8
virtualenv==20.0.18
watchdog==0.10.2
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.0
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.11.2
xlrd==1.2.0
XlsxWriter==1.2.7
xlwings==0.17.1
xlwt==1.3.0
xmltodict==0.12.0
yapf==0.28.0
zict==1.0.0
zipp==2.2.0

**Comment by sorend** [comment]
@alanthomass Your code does not compile here:
`TypeError: unsupported operand type(s) for ^: 'float' and 'int'`

(in your use of ^2)

**Comment by alanthomass** [comment]
Hey, i havent used ^ 2 in my actual code. I was unable to type it as such here. I used  **2 . I made the change above. Kindly help me out. Thanks :)  Python version 3.7.6

**Comment by alanthomass** [comment]
`return 0.0358 +(0.7349*x1) + (.0578*x2)-(0.3151*x3) + (0.6888*x4) + (0.1803*(x1**2)) - (0.0481* 
       (x2**2)) + (0.1699*(x3**2)) - (0.0494*(x4**2))- (0.3555*(x1*x2)) - (0.6316*(x1*x3)) + (0.5973* 
       (x1*x4)) + (0.0826*(x2*x3)) - (0.4736*(x2*x4)) -  (0.6547*(x3*x4))`

**Comment by alanthomass** [comment]
``import` pandas as pd
import numpy as np
from fylearn.ga import UnitIntervalGeneticAlgorithm, helper_fitness, helper_n_generations
from fylearn.local_search import LocalUnimodalSamplingOptimizer, helper_num_runs
from fylearn.tlbo import TeachingLearningBasedOptimizer
def fitness(X):
        print("X", X, "len", len(X))
        x1, x2, x3, x4 = X.tolist()
        return 0.0358 +(0.7349*x1) + (.0578*x2)-(0.3151*x3) + (0.6888*x4) + (0.1803*(x1**2)) -(0.0481* 
       (x2**2)) + (0.1699*(x3**2)) - (0.0494*(x4**2))- (0.3555*(x1*x2)) - (0.6316*(x1*x3)) + (0.5973* 
       (x1*x4)) + (0.0826*(x2*x3)) - (0.4736*(x2*x4)) -  (0.6547*(x3*x4))

lower_bounds = np.array([-10,-10,-10,-10])
upper_bounds = np.array([10,10,10,10])
    

tlbo = TeachingLearningBasedOptimizer(fitness, lower_bounds, upper_bounds)
tlbo = helper_n_generations(tlbo, 100)
best_solution, best_fitness = tlbo.best()
print("TLBO solution", best_solution, "fitness", best_fitness)``

**Comment by sorend** [comment]
From your pip freeze:
`fylearn==0.1.8`

You need to upgrade to the version with the fix (0.1.9)

**Comment by alanthomass** [comment]
I upgraded to fylearn 0.1.9 now. It didnt solve the issue. It gives the same error.

**Comment by alanthomass** [comment]
Hey, Thank You very much for the prompt responses. The problem is fixed. TLBO is running :)

**Comment by sorend** [comment]
Thanks for reporting back.
