### ISSUE TITLE
Random state in local_search optimizers

### ISSUE THREAD

**Issue by chkoar** [sorend/fylearn#2]
Hello,

You have done very good work here!

If I pass an integer as random_state in local_search optimizers I get `AttributeError: 'int' object has no attribute 'rand'`.
In other places like in JayaOptimizer you catch this.

Since you have scikit-learn as hard dependency I would suggest to use the check_random_state utility function to create the random number generator object

http://scikit-learn.org/stable/modules/generated/sklearn.utils.check_random_state.html#sklearn.utils.check_random_state

I could send a PR for this change.

**Comment by sorend** [comment]
Thanks for noticing and recommending solution. I'm unfortunately in
hospital at the moment so please send me a pull request (great if some
tests are included but up to you)

Best regards,
Soren

**Comment by chkoar** [comment]
I wish you a fast recovery. I will send a PR during the weekend.

Regards,
Chris

**Comment by sorend** [comment]
I'm closing this one again from your PR and commit #4718626 . Thanks again!
