### ISSUE TITLE
Constrained Optimisation

### ISSUE THREAD

**Issue by alanthomass** [sorend/fylearn#20]
Do you have an example of constrained optimisation using TLBO?

**Comment by sorend** [comment]
TLBO is no different for constrained problems.

As with other optmisation problems you can add the constraints as penalties.

I've taken the paper's example here:
https://github.com/sorend/fylearn/blob/master/tests/test_tlbo.py#L87

Best regards,
Søren

**Comment by alanthomass** [comment]
Thank you. You helped me understand this algorithm.:)
