### ISSUE TITLE
Iteration results

### ISSUE THREAD

**Issue by alanthomass** [sorend/fylearn#21]
Hey, is it possible to obtain the results of each iteration like a history?

**Comment by sorend** [comment]
For most of the optimizers implemented in the library, there are two functions:
* next()  -- next iteration of the optimizer
* best(..) -- returns best individual from the optimization

You can write a loop over those two to keep the history.

**Comment by sorend** [comment]
Closing the issue. Feel free to re-open if you need clarification.

BR,
Søren
