### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by abbasyazdinejad** [sorend/fylearn#27]
It will be more viable if you provide some samples to apply to this library.

**Comment by sorend** [comment]
Hi @abbasyazdinejad 
Greeting, and thanks for your comment. Any specific part of it you'd like samples of?

BR, Søren

**Comment by abbasyazdinejad** [comment]
Implementing a DNN model with fuzzy.

**Comment by sorend** [comment]
Hi again @abbasyazdinejad 
You will need a numpy based implementation of DNN if you're going to use fylearn. It's probably the fuzzylogic.py which is most interest to you. It's not very large, so you should easily be able to copy the parts you need (guessing sets, and perhaps also the aggregation rules?)

BR, Søren
