### ISSUE TITLE
in Pattern tree Classifier ==> fpt.FuzzyPatternTreeClassifier() I am not able to see the function score()

### ISSUE THREAD

**Issue by Gowthamgit04** [sorend/fylearn#29]
Under tests ==> test_fpt.py ==> 

l = fpt.FuzzyPatternTreeClassifier()
    l.fit(X, y)
    score = l.score(X, y)
    print("score", score)  

I am not able to find the score function in main  fpt.FuzzyPatternTreeClassifier() classifier as well can you please help on this

**Comment by sorend** [comment]
Hi.

Thanks for your interest in fylearn.

The score method is defined in ClassifierMixin from scikit learn, which the class inherits from.

Hope it helps. Feel free to ask further questions should they arrive.

Br,
Søren

**Comment by Gowthamgit04** [comment]
Hi Soren Sir Thanks for response
