### ISSUE TITLE
population elements in heuristic search methods

### ISSUE THREAD

**Issue by echo66** [sorend/fylearn#4]
Greetings!

I'm trying to find if it is possible to use arbitrary numpy arrays as elements of the population for the search methods in the library. Or, even better, objects or dictionaries. Can you shed a light on that? Thanks in advance!

**Comment by sorend** [comment]
You can for the GA, using DiscreteGeneticAlgorithm (you'd have to define your domain).

Let me know if this is what you are searching for.

**Comment by echo66** [comment]
Hmmm I see, thanks! :+1: 

What about the other algorithms? Do they work for arbitrary numpy arrays, objects or dictionaries? Or just single scalars?

**Comment by sorend** [comment]
```
>>> import numpy as np
>>> a = np.array(["a"])
>>> b = np.array(["b"])
>>> b - a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U1') dtype('<U1') dtype('<U1')
```
This kind of thing would need to work. I don't know if you can implement your own operations for arbitrary data types in numpy, if yes, then it will work, if no, then not.

It's possible to implement support in fylearn, but, would need a strong use-case for it (or, a pull-request :) )
