### ISSUE TITLE
Improve bibliography

### ISSUE THREAD

**Issue by kapec94** [sorend/fylearn#5]
Please add more info about articles you've referred to when implementing classifiers. Currently provided bibliography entries are incomplete.

For example:
[fylearn/fpt.py at master](/sorend/fylearn/blob/master/fylearn/fpt.py):

    References:
    [1] Hwong, 2009.
    [2] Senge and Huellemeier, 2009.
    [3] Senge and Huellemeier, 2010.

#### Ad. 1
I believe the guy's name is *Huang*.

#### Ad. 2
There is one article from 2009 that I found. It's "Learning Pattern Tree Classifiers Using a
Co-Evolutionary Algorithm" and this doesn't sound right at all, considering that it's not about top-down fuzzy pattern trees, or so it seems.

Another article, which probably is the right one, is "Top-Down Induction of Fuzzy Pattern Trees" by those guys. More or less. Latter's name is *Hüllermeier*. Also, from what I see, it's from 2011, not 2009...

Please provide more info when you cite an article. This will be really helpful.

**Comment by sorend** [comment]
Thanks for your notice.  1+2 have been fixed up.
