### ISSUE TITLE
I find  FuzzyPatternClassifier give all zero proba about all classies for one sample

### ISSUE THREAD

**Issue by haowuliao** [sorend/fylearn#8]
I give s sample code:

from fylearn.nfpc import FuzzyPatternClassifier
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
X = iris.data
y = iris.target
c = FuzzyPatternClassifier()
pro = c.fit(X, y).predict_proba(X)
pro_sum = pro.sum(axis=1)
print(pro_sum[np.where(pro_sum==0)].shape)

I finally get result ,   (12,)

**Comment by sorend** [comment]
Thanks @haowuliao -- fixed in 0.1.4

BR, Soren
